import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
const license = readFileSync(new URL('../src/vendor/bloub/LICENSE', import.meta.url), 'utf8');
const result = await build({entryPoints:[new URL('../src/bloub-motion.ts',import.meta.url).pathname],bundle:true,format:'iife',globalName:'MochiMotion',platform:'browser',target:'es2022',minify:true,write:false,banner:{js:`/*! bloub 0.1.1 (b4bb3c1)\n${license}*/`}});
export const motionSource = result.outputFiles[0].text;
writeFileSync(new URL('../../../apps/desktop/electron/dsh/bloub-motion.generated.ts',import.meta.url), `// Generated by jxl-brand/scripts/build-motion.mjs; edit the shared source.\nexport const BLOUB_MOTION_SOURCE = ${JSON.stringify(motionSource)};\n`);
console.log('Shared bloub runtime:', Buffer.byteLength(motionSource), 'bytes');
