import { createServer } from 'node:http';
import { extname, basename } from 'node:path';
import { createHash } from 'node:crypto';
import { OfficeVersionStore, documentKey, signJwt, verifyJwt } from './index.mjs';

const json=(res,status,value)=>{const body=Buffer.from(JSON.stringify(value));res.writeHead(status,{'content-type':'application/json','content-length':body.length,'cache-control':'no-store'});res.end(body);};
const typeFor=(ext)=>ext==='.xlsx'?'cell':ext==='.pptx'?'slide':'word';
async function body(req,max=64*1024){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw Object.assign(new Error('request too large'),{code:'OFFICE_CALLBACK_TOO_LARGE'});chunks.push(chunk);}return Buffer.concat(chunks);}
export function createOfficeServer(options){
 const store=new OfficeVersionStore(options); const engineOrigin=new URL(options.engineOrigin).origin; const publicBaseUrl=new URL(options.publicBaseUrl); if(publicBaseUrl.username||publicBaseUrl.password)throw new Error('publicBaseUrl credentials are forbidden');
 const browserOrigins=new Set(options.browserOrigins??[]); const callbackReachable=options.callbackReachable===true;
 async function engineOnline(){try{const r=await fetch(`${engineOrigin}/healthcheck`,{signal:AbortSignal.timeout(1500),redirect:'error'});return r.ok;}catch{return false;}}
 return createServer(async(req,res)=>{try{
  const requestOrigin=req.headers.origin;if(requestOrigin&&browserOrigins.has(requestOrigin)){res.setHeader('access-control-allow-origin',requestOrigin);res.setHeader('vary','Origin');res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');res.setHeader('access-control-allow-headers','Content-Type,Authorization');} if(req.method==='OPTIONS')return res.writeHead(requestOrigin&&browserOrigins.has(requestOrigin)?204:403).end();
  const url=new URL(req.url,'http://127.0.0.1'); const match=/^\/api\/office\/documents\/([A-Za-z0-9_-]{1,80})\/(editor-config|content|versions|callback)$/.exec(url.pathname);
  if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,engine:{origin:engineOrigin,online:await engineOnline(),callbackReachable},demoIds:[...store.documents.keys()]});
  if(!match)return json(res,404,{error:'not_found'}); const [,id,action]=match;
  if(req.method==='GET'&&action==='versions'){const versions=await store.versions(id);return json(res,200,{id,versions:versions.map(({version,name})=>({version,name}))});}
  if(req.method==='GET'&&action==='content'){const claims=verifyJwt(url.searchParams.get('token'),options.jwtSecret);if(claims.scope!=='office-read'||claims.documentId!==id||claims.exp*1000<Date.now()||!Number.isSafeInteger(claims.version))throw Object.assign(new Error('read token invalid'),{code:'OFFICE_JWT_INVALID'});const path=await store.atVersion(id,claims.version),bytes=await import('node:fs/promises').then(fs=>fs.readFile(path));if(createHash('sha256').update(bytes).digest('hex')!==claims.sha256)throw Object.assign(new Error('document changed after config issuance'),{code:'OFFICE_VERSION_CHANGED'});res.writeHead(200,{'content-type':'application/octet-stream','content-length':bytes.length,'content-disposition':`inline; filename="${basename(path).replaceAll('"','')}"`,'cache-control':'no-store'});return res.end(bytes);}
  if(req.method==='GET'&&action==='editor-config'){if(!await engineOnline())return json(res,503,{error:'engine_offline',engineOrigin});if(!callbackReachable)return json(res,503,{error:'callback_bridge_unverified',engineOrigin});const versions=await store.versions(id),version=versions.at(-1)?.version??0,path=await store.atVersion(id,version),bytes=await import('node:fs/promises').then(fs=>fs.readFile(path)),sha256=createHash('sha256').update(bytes).digest('hex'),ext=extname(path).slice(1).toLowerCase(),now=Math.floor(Date.now()/1000);const read=signJwt({scope:'office-read',documentId:id,version,sha256,exp:now+300},options.jwtSecret);const config={document:{fileType:ext,key:documentKey(id,sha256),title:basename(path),url:new URL(`/api/office/documents/${id}/content?token=${read}`,publicBaseUrl).href,permissions:{edit:true,download:true}},documentType:typeFor(`.${ext}`),editorConfig:{callbackUrl:new URL(`/api/office/documents/${id}/callback`,publicBaseUrl).href,mode:'edit',user:{id:'mochi-demo-teacher',name:'Mochi 演示教师'}},type:'desktop'};return json(res,200,{engineOrigin,scriptUrl:`${engineOrigin}/web-apps/apps/api/documents/api.js`,config:{...config,token:signJwt(config,options.jwtSecret)}});}
  if(req.method==='POST'&&action==='callback')return json(res,200,await store.saveCallback({authorization:req.headers.authorization,body:await body(req),expectedId:id}));
  return json(res,405,{error:'method_not_allowed'});
 }catch(error){json(res,error.code==='OFFICE_DOCUMENT_DENIED'?404:400,{error:error.code??'OFFICE_REQUEST_FAILED'});}});
}

export function listenOfficeServer(options){const server=createOfficeServer(options);const host=options.host??'127.0.0.1',port=options.port??18100;if(host!=='127.0.0.1'&&host!=='::1')throw new Error('office adapter must bind loopback');return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,()=>resolve(server));});}
