import { MOCHI_PET_CSS, PET_PALETTES } from "./pet-palettes.generated";
import { MOCHI_CONTROLS_CSS } from "./controls.generated";
import { BLOUB_MOTION_SOURCE } from "./bloub-motion.generated";
import { MECHANICAL_AUDIO_SOURCE } from "./mechanical-audio.generated";
import type { RailSurface } from "./protocol";

/**
 * [Mochi 2026-09-18] 常驻条 / 喊人弹窗的自包含页面。
 *
 * 为什么是字符串而不是打包静态资源：
 * - 不走 Harness 静态路由，不需要新增 CSP 放行，也不需要进插件白名单与快照清单；
 * - 与 main.ts 里既有的启动页/错误页同一个路子（data: URL）。
 *
 * 安全约定：页面里显示的数据全部来自 renderer 经 IPC 送来的字符串，因此一律用
 * textContent 建 DOM，绝不拼 innerHTML。此文件不加载任何外部字体/脚本/图片。
 */

/** 两块屏共用的一套配色：纸白机身 + 墨色文字 + 克制黄铜强调（对齐 calm-tokens）。 */
const PALETTE = [
  "--mochi-canvas:#f6f3ec",
  "--mochi-canvas-raised:#fffdf8",
  "--mochi-line:rgba(76,66,47,.17)",
  "--mochi-paper:#34332f",
  "--mochi-paper-dim:#706b60",
  "--mochi-accent:#dec49d",
  "--mochi-ok:#d8c9b6",
  "--mochi-bad:#d9776b",
  "--mochi-bad-text:#9f493d",
  "--mochi-attention-text:#8b632a",
  "--mochi-ok-text:#665340",
].join(";");

const BASE_CSS = [
  "*{box-sizing:border-box}",
  "@media(prefers-color-scheme:dark){:root{--mochi-canvas:#242320;--mochi-canvas-raised:#302d28;--mochi-line:rgba(231,221,202,.2);--mochi-paper:#f1ede4;--mochi-paper-dim:#b4ac9e;--mochi-bad-text:#efb0a6;--mochi-attention-text:#e1c38d;--mochi-ok-text:#eee0ce}body{color-scheme:dark!important}}",
  "html,body{margin:0;block-size:100%;overflow:hidden;background:transparent}",
  "body{color-scheme:light;color:var(--mochi-paper);font:400 13px/1.5 'PingFang SC','Noto Sans CJK SC','Microsoft YaHei',system-ui,sans-serif;-webkit-font-smoothing:antialiased}",
  ".drag{-webkit-app-region:drag}",
  ".nodrag{-webkit-app-region:no-drag}",
  ".shell{display:flex;flex-direction:column;block-size:100%;border:1px solid var(--mochi-line);border-radius:14px;overflow:hidden;background:var(--mochi-canvas)}",
  ".shell--teacher{border-color:var(--mochi-line);background:var(--mochi-canvas);box-shadow:0 6px 18px rgba(65,53,33,.08)}",
  "header{display:flex;align-items:center;gap:8px;padding:10px 12px;border-block-end:1px solid var(--mochi-line);background:var(--mochi-canvas-raised)}",
  ".shell--teacher header,.shell--teacher footer{background:var(--mochi-canvas-raised)}",
  "header h1{margin:0;font-size:14px;font-weight:500}",
  ".count{margin-inline-start:auto;padding:1px 8px;border-radius:999px;background:var(--mochi-accent);color:#1d2a23;font-size:11px;font-weight:500}",
  "button{font:inherit;cursor:pointer;border-radius:9px;border:1px solid var(--mochi-line);background:transparent;color:var(--mochi-paper)}",
  "button:not(#toggle){box-shadow:0 2px 0 var(--mochi-line);transition:transform 100ms ease,background-color 150ms ease}button:not(#toggle):active{transform:translateY(2px);box-shadow:none}button:hover{background:var(--mochi-canvas-raised)}",
  "button:focus-visible{outline:2px solid var(--mochi-accent);outline-offset:1px}",
  ".icon{inline-size:22px;block-size:22px;padding:0;line-height:1;font-size:15px;flex:none}",
  ".list{flex:1;min-block-size:0;overflow:auto;padding:8px 8px 16px;display:grid;gap:6px;align-content:start}",
  ".list,.pop__body,.pop__feedback{scrollbar-width:thin;scrollbar-color:var(--mochi-line) transparent}",
  ".row{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:start;padding:8px 9px;border:1px solid var(--mochi-line);border-radius:11px;background:var(--mochi-canvas-raised);cursor:pointer}",
  ".row:hover{border-color:var(--mochi-paper-dim)}",
  ".row:focus-visible{outline:2px solid var(--mochi-accent);outline-offset:1px}",
  ".row[data-tone='attention']{border-color:rgba(217,151,62,.55)}",
  ".row[data-tone='ok']{border-color:rgba(183,169,149,.65)}",
  ".row[data-tone='bad']{border-color:rgba(217,119,107,.6)}",
  ".seq{inline-size:20px;block-size:20px;border-radius:6px;display:grid;place-items:center;background:var(--mochi-canvas);font-size:11px;font-weight:500}",
  ".row[data-tone='attention'] .seq{background:var(--mochi-accent);color:#1d2a23}",
  ".row[data-tone='bad'] .seq{background:var(--mochi-bad);color:#2a1a18}",
  ".row[data-tone='ok'] .seq{background:var(--mochi-ok);color:#514335}",
  ".name{font-weight:600;overflow-wrap:anywhere}",
  ".meta{margin-block-start:1px;color:var(--mochi-paper-dim);font-size:11px;overflow-wrap:anywhere}",
  ".note{margin-block-start:3px;color:var(--mochi-paper);font-size:12px;overflow-wrap:anywhere}",
  ".context{margin-block-start:4px;padding-block-start:3px;border-block-start:1px solid rgba(255,255,255,.12);color:var(--mochi-paper-dim);font-size:11px;line-height:1.4;overflow-wrap:anywhere}",
  ".shell--teacher .name{font-size:14px;line-height:1.35}.shell--teacher .meta{font-size:12px;line-height:1.45}.shell--teacher .note{font-size:13px;line-height:1.45}.shell--teacher .context{font-size:12px;line-height:1.45}",
  ".badge{align-self:start;padding:2px 7px;border-radius:999px;font-size:11px;background:var(--mochi-canvas);white-space:nowrap}",
  ".row[data-tone='attention'] .badge{background:rgba(217,151,62,.22);color:var(--mochi-attention-text)}",
  ".row[data-tone='bad'] .badge{background:rgba(217,119,107,.24);color:var(--mochi-bad-text)}",
  ".row[data-tone='ok'] .badge{background:rgba(183,169,149,.24);color:var(--mochi-ok-text)}",
  ".empty{margin:auto;padding:14px;color:var(--mochi-paper-dim);font-size:12px;text-align:center}",
  "footer{display:flex;align-items:center;gap:8px;padding:7px 10px;border-block-start:1px solid var(--mochi-line);color:var(--mochi-paper-dim);font-size:11px}",
  "footer #detail{min-inline-size:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  "footer #updated{flex:none;white-space:nowrap}",
  "footer .grow{margin-inline-start:auto}",
  "footer button{padding:4px 10px;font-size:11px}",
  ".sr-only{position:absolute;inline-size:1px;block-size:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}",
  "body[data-sync='stale'] #updated{color:var(--mochi-attention-text)}",
  "@media (prefers-reduced-motion:no-preference){.shell{transition:transform 220ms cubic-bezier(.2,.75,.25,1),background-color 220ms ease,backdrop-filter 220ms ease}.row{transition:border-color 140ms ease,transform 140ms ease}.row:active{transform:scale(.985)}}",
  "@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}",
  "@media (prefers-reduced-transparency:reduce){.shell--teacher{background:var(--mochi-canvas)}.shell--teacher header,.shell--teacher footer{background:var(--mochi-canvas-raised)}}",
  "@media (prefers-contrast:more){.shell{background:var(--mochi-canvas);border-color:var(--mochi-paper)}.row{background:var(--mochi-canvas);border-color:var(--mochi-paper)}.meta,footer{color:var(--mochi-paper)}}",
  "body[data-surface='teacher-rail'][data-expanded='false'] header{justify-content:center;block-size:100%;padding:0;background:transparent;border:0}",
  "body[data-surface='teacher-rail'][data-expanded='true'] header h1{order:0}",
  "body[data-surface='teacher-rail'][data-expanded='true'] header{padding-inline-end:calc(var(--pet-size,96px)/2 - 18px)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .count{order:1;margin-inline-start:0}",
  "body[data-surface='teacher-rail'][data-expanded='true'] #hide{order:2;margin-inline-start:auto}",
  "body[data-surface='teacher-rail'][data-expanded='true'] #toggle{order:3;margin-inline-start:0}",
  "body[data-surface='teacher-rail'][data-expanded='false'] header h1,body[data-surface='teacher-rail'][data-expanded='false'] .count,body[data-surface='teacher-rail'][data-expanded='false'] #hide,body[data-surface='teacher-rail'][data-expanded='false'] .list,body[data-surface='teacher-rail'][data-expanded='false'] footer{display:none}",
  "#toggle{position:relative;inline-size:34px;block-size:34px;padding:0;border-radius:50%;font-weight:650;font-size:17px;background:rgba(255,255,255,.12)}",
  "#toggle .pet,#toggle .toggle-mark{display:none}",
  "#toggle.is-open .toggle-mark{display:inline}",
  "#pet-count-group{display:none}",
  "body[data-surface='teacher-rail'][data-expanded='false'][data-sync='stale'] #toggle::after{content:'';position:absolute;left:1px;bottom:2px;inline-size:9px;block-size:9px;border-radius:50%;background:var(--mochi-accent);box-shadow:0 0 0 2px var(--mochi-canvas)}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet{display:block;position:relative;inline-size:48px;block-size:58px;margin:auto}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet{transform:translateY(0) scale(1);transform-origin:50% 78%;transition:transform 320ms cubic-bezier(.2,.8,.25,1)}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle:hover .pet{transform:translateY(-1px) scale(1.025)}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle[data-pressed='true'] .pet{transform:translateY(2px) scale(1.09,.88);transition-duration:95ms}",
  "#toggle .pet__orb{position:absolute;inset:0 auto auto 0;inline-size:48px;block-size:48px;transform-origin:50% 86%;animation:none}",
  "#toggle .pet__body{fill:#a06a32;stroke:rgba(255,246,230,.2);stroke-width:.9}",
  "#toggle .pet__shadow{fill:rgba(69,88,78,.18)}",
  "#toggle .pet__gaze{transform:translate(var(--pet-gaze-x,0px),var(--pet-gaze-y,0px));transition:transform 180ms cubic-bezier(.2,.75,.25,1)}",
  "#toggle .pet__eyes{fill:#fff6e6;transform-box:fill-box;transform-origin:center;animation:pet-blink 5.6s ease-in-out infinite}",
  "#toggle .pet__laptop{position:absolute;left:50%;bottom:0;inline-size:78%;block-size:30px;transform:translateX(-50%);animation:pet-laptop-breathe 4.6s ease-in-out infinite}",
  "#toggle .pet__glyph{animation:none}",
  "#toggle .pet__thought{display:none!important;position:absolute;top:0;right:-3px;gap:2px;align-items:center;pointer-events:none}",
  "#toggle .pet__thought i{inline-size:3px;block-size:3px;border-radius:50%;background:#f4dfbd;animation:pet-think 1.2s ease-in-out infinite}",
  "#toggle .pet__thought i:nth-child(2){animation-delay:150ms}#toggle .pet__thought i:nth-child(3){animation-delay:300ms}",
  "body[data-surface='teacher-rail'][data-expanded='false'][data-sync='waiting'] #toggle:not([data-attention='true']) .pet__thought{display:flex}",
  "#pet-count-group{position:absolute;top:0;right:-5px;inline-size:19px;block-size:19px;overflow:visible}",
  "#toggle.is-open #pet-count-group{display:none!important}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle:active{transform:none}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle[data-pulse='true'] .pet__orb{animation:none}",
  "@keyframes pet-breathe{0%,100%{transform:scale(1)}50%{transform:scale(1.03,.98)}}",
  "@keyframes pet-alert{0%,100%{transform:rotate(0)}18%,54%{transform:rotate(-5deg)}36%,72%{transform:rotate(5deg)}}",
  "@keyframes pet-blink{0%,45%,48%,100%{transform:scaleY(1)}46.5%{transform:scaleY(.12)}}",
  "@keyframes pet-laptop-breathe{0%,100%{transform:translateX(-50%) translateY(0)}50%{transform:translateX(-50%) translateY(.8px)}}",
  "@keyframes pet-think{0%,100%{transform:translateY(0);opacity:.45}50%{transform:translateY(-2px);opacity:1}}",
  "@media (prefers-reduced-motion:reduce){body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__orb,body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__eyes,body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__laptop,body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__glyph,body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__thought i{animation:none!important}body[data-surface='teacher-rail'][data-expanded='false'] #toggle:hover .pet,body[data-surface='teacher-rail'][data-expanded='false'] #toggle[data-pressed='true'] .pet,body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__gaze{transform:none!important}body[data-surface='teacher-rail'][data-expanded='false'] #toggle:active{transform:none}}",
  "@media (prefers-contrast:more){.shell--teacher{transition:none}body[data-surface='teacher-rail'] #toggle{transition:none}}",
  // One quiet paper list, with tactile controls kept at the edges.
  "body[data-surface='teacher-rail'][data-expanded='true'] .shell--teacher{border-radius:16px;box-shadow:0 6px 18px rgba(65,53,33,.08)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] header{min-block-size:62px;padding:10px calc(var(--pet-size,96px)/2 - 18px) 10px 18px;gap:8px;background:var(--mochi-canvas)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] header h1{font-size:16px;font-weight:600;line-height:1.4;letter-spacing:0;color:var(--mochi-paper)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .count{padding:0 4px;background:none;color:var(--mochi-paper-dim);font-size:12px;font-weight:400}",
  "body[data-surface='teacher-rail'][data-expanded='true'] #hide{inline-size:30px;block-size:30px;border-radius:9px;background:var(--mochi-canvas-raised)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] #toggle{border-radius:10px;background:var(--mochi-canvas-raised);box-shadow:0 2px 0 var(--mochi-line)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .list{margin:0 16px;padding:0 0 8px;gap:0}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .row{position:relative;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:12px 3px;border:0;border-bottom:1px solid var(--mochi-line);border-radius:0;background:transparent;box-shadow:none;color:var(--mochi-paper)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .row:hover{background:var(--mochi-canvas-raised)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .seq{display:none}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .name{font-size:15px;font-weight:600;line-height:1.4}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .meta{margin-top:3px;font-size:11px;color:var(--mochi-paper-dim)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .note{margin-top:9px;font-size:13px;line-height:1.5;font-weight:400}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .context{margin-top:4px;padding:0;border:0;font-size:12px;color:var(--mochi-paper-dim)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .badge{padding:3px 0;background:none;border-radius:0;color:var(--mochi-paper-dim);font-size:11px;font-weight:400}",
  "body[data-surface='teacher-rail'][data-expanded='true'] .row[data-tone='bad'] .badge{color:var(--mochi-bad-text)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] footer{min-block-size:48px;padding:9px 14px;background:var(--mochi-canvas)}",
  "body[data-surface='teacher-rail'][data-expanded='true'] footer #open{padding:7px 11px;background:var(--mochi-canvas-raised);font-weight:500}",
  "body[data-surface='teacher-rail'][data-expanded='false'] .shell{border:0;border-radius:0;background:transparent;box-shadow:none;-webkit-backdrop-filter:none;backdrop-filter:none;overflow:visible}",
  "body[data-surface='teacher-rail'][data-expanded='false'] header{background:transparent;-webkit-backdrop-filter:none;backdrop-filter:none}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle{inline-size:var(--pet-size,96px);block-size:var(--pet-size,96px);padding:0;border:0;background:transparent;box-shadow:none;-webkit-backdrop-filter:none;backdrop-filter:none}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle::before{content:none}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet{inline-size:calc(var(--pet-size,96px)*.8333);block-size:calc(var(--pet-size,96px)*.9583)}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__orb{inline-size:calc(var(--pet-size,96px)*.8333);block-size:calc(var(--pet-size,96px)*.8333)}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet__laptop{block-size:calc(var(--pet-size,96px)*.4792)}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle .pet{z-index:1}",
  "body[data-surface='teacher-rail'][data-expanded='false'] #toggle:focus-visible{outline:2px solid #d9bd91;outline-offset:-2px}",
  "#pet-resize{display:none;position:absolute;right:0;bottom:0;width:20px;height:20px;padding:0;border:0;border-radius:0;background:transparent;box-shadow:none;cursor:nwse-resize;touch-action:none;-webkit-app-region:no-drag;z-index:9}body[data-surface='teacher-rail'][data-expanded='false'] #pet-resize{display:block}#pet-resize:focus-visible{outline:1px solid var(--mochi-muted);outline-offset:-3px}",
  ".shell--teacher{position:relative}.departures{position:absolute;inset:0;z-index:5;pointer-events:none;overflow:hidden;border-radius:inherit}.departures .row{position:absolute;pointer-events:none;transform-origin:12% 12%;will-change:transform,opacity}",
  "@media (prefers-reduced-motion:no-preference){body[data-surface='teacher-rail'][data-expanded='true'] .row:hover{transform:none}body[data-surface='teacher-rail'] footer #open:active{transform:scale(.97)}}",
  "@media (prefers-reduced-transparency:reduce){body[data-surface='teacher-rail'][data-expanded='true'] .shell--teacher{background:var(--mochi-canvas);backdrop-filter:none}body[data-surface='teacher-rail'][data-expanded='true'] header,body[data-surface='teacher-rail'][data-expanded='true'] footer{background:var(--mochi-canvas-raised);backdrop-filter:none}}",
  "@media (prefers-contrast:more){body[data-surface='teacher-rail'][data-expanded='true'] .shell--teacher{background:var(--mochi-canvas);border-color:var(--mochi-paper);box-shadow:none}body[data-surface='teacher-rail'][data-expanded='true'] .row{background:var(--mochi-canvas-raised);border-color:var(--mochi-paper);box-shadow:none}body[data-surface='teacher-rail'][data-expanded='true'] #toggle{background:var(--mochi-canvas);border-color:var(--mochi-paper)}body[data-surface='teacher-rail'][data-expanded='true'] footer #open{background:var(--mochi-accent);border-color:var(--mochi-paper)}body[data-surface='teacher-rail'][data-expanded='false'] .shell,body[data-surface='teacher-rail'][data-expanded='false'] #toggle{background:transparent;border:0;box-shadow:none}}",
].join("");

/** 教室屏要给一整个班看，整体放大一档、对比更高。 */
const BOARD_CSS = [
  "body{font-size:15px}",
  "header h1{font-size:17px}",
  ".row{padding:11px 12px}",
  ".seq{inline-size:26px;block-size:26px;font-size:13px}",
  ".name{font-size:16px}",
  ".meta{font-size:13px}",
  ".note{font-size:14px}",
  ".badge{font-size:12px}",
].join("");

const POPUP_CSS = [
  "body{font-size:14px;background:transparent!important;padding:8px 8px 8px 104px;overflow:hidden}",
  ".popup-pet{position:absolute;left:4px;top:24px;width:96px;height:96px;pointer-events:none}.popup-pet svg{width:100%;height:100%}.popup-pet .pet__body{fill:#a06a32;stroke:#e1bd8c;stroke-width:.9}.popup-pet .pet__eyes{fill:#fff6e6;transform-box:fill-box;transform-origin:center;animation:pet-blink 5.6s ease-in-out infinite}.popup-pet .pet__shadow{fill:rgba(69,88,78,.18)}",
  ".pop{position:relative;overflow:visible!important;transform-origin:0 80%}.pop::before{content:'';position:absolute;left:-9px;top:56px;width:16px;height:16px;background:var(--mochi-canvas);border-left:1px solid var(--mochi-line);border-bottom:1px solid var(--mochi-line);transform:rotate(45deg)}.pop__bar{border-radius:16px 16px 0 0}.pop__bar .grow{flex:1}.pop__body{-webkit-app-region:no-drag}.pop__close{margin-left:10px;padding:2px 7px;font-size:16px}.pop__detail{color:var(--mochi-paper)!important}",
  "@media(prefers-reduced-motion:no-preference){.pop,.popup-pet{animation:mochi-message-in 280ms ease-out}body[data-leaving='true'] .pop,body[data-leaving='true'] .popup-pet{animation:mochi-message-out 220ms ease-in forwards}@keyframes mochi-message-in{from{opacity:0;transform:translateY(14px) scale(.94)}to{opacity:1;transform:none}}@keyframes mochi-message-out{to{opacity:0;transform:translateY(12px) scale(.94)}}}",
  "@media(prefers-reduced-motion:no-preference){.pop__body{animation:paper-arrive 400ms cubic-bezier(.2,.7,.2,1)}@keyframes paper-arrive{from{opacity:.3;transform:translateY(-12px)}to{opacity:1;transform:translateY(0)}}}",
  ".pop{display:flex;flex-direction:column;block-size:100%;border:1px solid var(--mochi-line);border-radius:16px;overflow:hidden;background:var(--mochi-canvas)}",
  ".pop__bar{display:flex;align-items:center;padding:9px 12px;background:var(--mochi-canvas-raised);color:var(--mochi-paper-dim);border-bottom:1px solid var(--mochi-line);font-size:12px;font-weight:500}",
  ".pop__body{flex:1;min-block-size:0;display:flex;flex-direction:column;justify-content:flex-start;gap:5px;padding:16px 18px;overflow:auto}",
  ".pop__title{flex:none;margin:0;font-size:20px;line-height:1.25;font-weight:500}",
  ".pop__subject{flex:none;font-size:16px;line-height:1.3;font-weight:500;overflow-wrap:anywhere}",
  ".pop__detail{flex:none;color:var(--mochi-paper-dim);font-size:13px;line-height:1.4;white-space:pre-wrap;overflow-wrap:anywhere}",
  ".pop__feedback{flex:none;min-block-size:16px;max-block-size:42px;padding:0 16px 8px;overflow:auto;color:var(--mochi-bad-text);font-size:12px}",
  ".pop__actions{flex:none;display:flex;gap:8px;padding:0 16px 12px}",
  ".pop__actions button{padding:9px 14px;font-size:13px}",
  ".pop__actions .primary{background:var(--mochi-accent);border-color:var(--mochi-accent);color:#231a0d;font-weight:500}",
].join("");

/** 页面里最小的一层工具函数。刻意不用模板字符串，避免与外层字符串冲突。 */
const PAGE_HELPERS = [
  "var bridge = window.mochiRail || null;",
  "var petPalettes = " + JSON.stringify(PET_PALETTES.map(p => p.id)) + ";if(bridge && bridge.onPetPalette)bridge.onPetPalette(function(value){if(petPalettes.indexOf(value)>=0)document.documentElement.dataset.mochiPetPalette=value;});",
  "var uiAudio = (" + MECHANICAL_AUDIO_SOURCE + ")(window, false);uiAudio.bind(document);",
  "if(bridge && bridge.onSoundPreference)bridge.onSoundPreference(function(enabled){uiAudio.setEnabled(enabled);document.body.dataset.uiSound=enabled===true?'on':'off';});",
  "window.addEventListener('pagehide',function(){uiAudio.dispose();},{once:true});",
  "function el(tag, className, value){",
  "  var node = document.createElement(tag);",
  "  if (className) node.className = className;",
  "  if (value !== undefined && value !== null) node.textContent = String(value);",
  "  return node;",
  "}",
  "function pad(n){ return String(n).padStart(2, '0'); }",
  "function stamp(value){",
  "  var ms = Date.parse(String(value || ''));",
  "  if (!isFinite(ms)) return '';",
  "  var d = new Date(ms);",
  "  return pad(d.getHours()) + ':' + pad(d.getMinutes());",
  "}",
  "function recentStamp(value){",
  "  var ms = Date.parse(String(value || ''));",
  "  if (!isFinite(ms)) return '';",
  "  var d = new Date(ms), now = new Date();",
  "  var time = pad(d.getHours()) + ':' + pad(d.getMinutes());",
  "  return d.toDateString() === now.toDateString() ? time : pad(d.getMonth() + 1) + '/' + pad(d.getDate()) + ' ' + time;",
  "}",
  "function act(action){ if (bridge && bridge.act) bridge.act(action); }",
].join("\n");

const RAIL_SCRIPT = [
  PAGE_HELPERS,
  BLOUB_MOTION_SOURCE,
  "var petSvg = document.querySelector('.pet__orb');",
  "var petMotion = petSvg ? MochiMotion.mountMotion(petSvg, {state:'idle'}) : null;",
  "function syncPetMotion(restart){ if(petMotion) petMotion.update({state:syncStatus==='stale'?'error':Number(document.getElementById('toggle').dataset.totalPending)>0?'alert':syncStatus==='waiting'?'thinking':'idle',active:!expanded,restart:restart===true}); }",
  "window.addEventListener('pagehide',function(){if(petMotion)petMotion.dispose();},{once:true});",
  "var SURFACE = document.body.dataset.surface;",
  "var lastPendingIds = null;",
  "var lastPendingTotal = null;",
  "var renderRevision = 0;",
  "var syncStatus = 'waiting';",
  "function toggleLabel(value, pending){ return (value ? '收起' : '展开') + ' Mochi 待办' + (pending ? '，' + pending + ' 条待处理' : '') + (syncStatus === 'stale' ? '，同步中断，待办可能不是最新' : syncStatus === 'waiting' ? '，尚未同步' : ''); }",
  "function setSyncHealth(payload){",
  "  if (!payload || !['waiting','live','stale'].includes(payload.status)) return;",
  "  var previous = syncStatus; syncStatus = payload.status; document.body.dataset.sync = syncStatus;",
  "  var last = recentStamp(payload.lastSuccessAt);",
  "  var label = syncStatus === 'stale' ? ('同步中断' + (last ? ' · ' + last : '')) : syncStatus === 'waiting' ? '尚未同步' : '已同步';",
  "  var updated = document.getElementById('updated');",
  "  if (updated.textContent !== label) updated.textContent = label;",
  "  updated.title = syncStatus === 'stale' ? (last ? '上次成功同步：' + new Date(payload.lastSuccessAt).toLocaleString() : '尚未成功同步') : '';",
  "  var toggle = document.getElementById('toggle');",
  "  if (toggle) toggle.setAttribute('aria-label', toggleLabel(expanded, Number(toggle.dataset.totalPending) || 0));",
  "  syncPetMotion();",
  "  if (previous !== syncStatus && syncStatus === 'stale') document.getElementById('sync-announcement').textContent = '同步中断，显示的是上次保存的待办。';",
  "  if (previous === 'stale' && syncStatus === 'live') document.getElementById('sync-announcement').textContent = '同步已恢复。';",
  "}",
  "function renderRow(row){",
  "  var node = el('article', 'row');",
  "  node.dataset.id = row.id;",
  "  node.dataset.actionRequired = String(row.actionRequired === true);",
  "  node.tabIndex = 0;",
  "  node.setAttribute('role', 'button');",
  "  node.setAttribute('aria-label', '打开 ' + row.name + ' 的待办。' + [row.meta, row.note, row.context, row.badge].filter(Boolean).join('。'));",
  "  node.dataset.tone = row.tone;",
  "  node.appendChild(el('span', 'seq', row.seq));",
  "  var main = el('div');",
  "  main.appendChild(el('div', 'name', row.name));",
  "  if (row.meta) main.appendChild(el('div', 'meta', row.meta));",
  "  if (row.note) main.appendChild(el('div', 'note', row.note));",
  "  if (row.context) main.appendChild(el('div', 'context', row.context));",
  "  node.appendChild(main);",
  "  if (row.badge) node.appendChild(el('span', 'badge', row.badge));",
  "  function openRow(){ act({ type: 'open', id: row.id }); }",
  "  node.addEventListener('click', openRow);",
  "  node.addEventListener('keydown', function(event){ if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openRow(); } });",
  "  return node;",
  "}",
  "function render(snapshot){",
  "  var revision = ++renderRevision;",
  "  document.getElementById('heading').textContent = snapshot.heading || '待办';",
  "  document.getElementById('detail').textContent = snapshot.detail || '';",
  "  var count = document.getElementById('count');",
  "  var pendingRows = snapshot.rows.filter(function(row){ return row.actionRequired === true; });",
  "  var pendingIds = new Set(pendingRows.map(function(row){ return row.id; }));",
  "  var hasNewPending = lastPendingIds !== null && pendingRows.some(function(row){ return !lastPendingIds.has(row.id); });",
  "  var totalPending = Number.isSafeInteger(snapshot.actionRequiredCount) ? Math.max(0, snapshot.actionRequiredCount) : pendingRows.length;",
  "  if (lastPendingTotal !== null && totalPending > lastPendingTotal) hasNewPending = true;",
  "  var completed = lastPendingTotal !== null && totalPending < lastPendingTotal;",
  "  lastPendingIds = pendingIds;",
  "  lastPendingTotal = totalPending;",
  "  var visibleCount = SURFACE === 'classroom-board' ? (Number.isSafeInteger(snapshot.totalRowCount) ? Math.max(0, snapshot.totalRowCount) : snapshot.rows.length) : totalPending;",
  "  count.textContent = String(visibleCount);",
  "  count.hidden = visibleCount === 0;",
  "  var toggle = document.getElementById('toggle');",
  "  if (toggle) {",
  "    var pending = totalPending;",
  "    toggle.dataset.count = pending ? String(pending > 9 ? '9+' : pending) : '';",
  "    toggle.dataset.totalPending = String(pending);",
  "    toggle.dataset.attention = pending ? 'true' : 'false';",
  "    if (hasNewPending && !expanded) { toggle.dataset.pulse = 'false'; void toggle.offsetWidth; toggle.dataset.pulse = 'true'; }",
  "    else toggle.dataset.pulse = 'false';",
  "    document.getElementById('pet-count').textContent = toggle.dataset.count;",
  "    document.getElementById('pet-count-group').style.display = pending ? 'block' : 'none';",
  "    toggle.setAttribute('aria-label', toggleLabel(expanded, pending));",
  "  }",
  "  syncPetMotion(hasNewPending);",
  "  var list = document.getElementById('list');",
  "  var focused = document.activeElement && document.activeElement.classList.contains('row') ? document.activeElement.dataset.id : '';",
  "  var scrollTop = list.scrollTop;",
  "  var leaving = [];",
  "  if (SURFACE === 'teacher-rail' && expanded && completed && !matchMedia('(prefers-reduced-motion: reduce)').matches) {",
  "    var shellRect = document.getElementById('shell').getBoundingClientRect();",
  "    list.querySelectorAll('.row[data-action-required=\"true\"]').forEach(function(node){",
  "      if (pendingIds.has(node.dataset.id) || leaving.length >= 2) return;",
  "      var rect = node.getBoundingClientRect();",
  "      leaving.push({ node: node.cloneNode(true), x: rect.left - shellRect.left, y: rect.top - shellRect.top, width: rect.width, height: rect.height });",
  "    });",
  "  }",
  "  list.replaceChildren();",
  "  if (snapshot.rows.length === 0) {",
  "    list.appendChild(el('p', 'empty', SURFACE === 'classroom-board' ? '当前没有需要展示的名单。' : '当前没有待处理的学生预约。'));",
  "  } else {",
  "    for (var i = 0; i < snapshot.rows.length; i++) list.appendChild(renderRow(snapshot.rows[i]));",
  "  }",
  "  leaving.forEach(function(item){",
  "    var ghost = item.node; ghost.setAttribute('aria-hidden', 'true'); ghost.removeAttribute('role'); ghost.tabIndex = -1;",
  "    ghost.style.left = item.x + 'px'; ghost.style.top = item.y + 'px'; ghost.style.width = item.width + 'px'; ghost.style.height = item.height + 'px';",
  "    document.getElementById('departures').appendChild(ghost);",
  "    var animation = ghost.animate([{ transform: 'translate3d(0,0,0) rotate(0deg)', opacity: 1 }, { transform: 'translate3d(18px,-10px,0) rotate(4deg)', opacity: 0 }], { duration: 420, easing: 'cubic-bezier(.2,.75,.25,1)' });",
  "    animation.finished.then(function(){ ghost.remove(); }, function(){ ghost.remove(); });",
  "  });",
  "  if (focused) { var restored = list.querySelector('.row[data-id=\\\"' + CSS.escape(focused) + '\\\"]'); if (restored) restored.focus({ preventScroll: true }); else if (toggle) toggle.focus({ preventScroll: true }); }",
  "  list.scrollTop = scrollTop;",
  "  requestAnimationFrame(function(){ if (revision === renderRevision && list.scrollTop === 0 && scrollTop > 0) list.scrollTop = scrollTop; });",
  "}",
  "var expanded = SURFACE === 'classroom-board';",
  "function setExpanded(value, notify){",
  "  if (SURFACE === 'classroom-board') return;",
  "  expanded = value;",
  "  document.body.dataset.expanded = String(value);",
  "  var button = document.getElementById('toggle');",
  "  button.setAttribute('aria-expanded', String(value));",
  "  var totalPending = Number(button.dataset.totalPending) || 0;",
  "  button.setAttribute('aria-label', toggleLabel(value, totalPending));",
  "  button.classList.toggle('is-open', value);",
  "  syncPetMotion();",
  "  if (value) { button.dataset.pressed = 'false'; }",
  "  if (notify) act({ type: 'toggle', reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)').matches });",
  "}",
  "function applyMainState(payload){",
  "  if (!payload || typeof payload !== 'object') return;",
  "  if (typeof payload.petSize === 'number') { petSize = Math.max(72, Math.min(160, payload.petSize)); document.documentElement.style.setProperty('--pet-size', petSize + 'px'); }",
  "  if (payload.type === 'state') { setExpanded(payload.expanded === true, false); return; }",
  "  if (typeof payload.expanded === 'boolean') setExpanded(payload.expanded, false);",
  "  render(payload);",
  "}",
  "var petSize = 96, resizePointer = null, resizeCorner = document.getElementById('pet-resize');",
  "if (resizeCorner) {",
  "  resizeCorner.addEventListener('pointerdown', function(e){ if(expanded || e.button !== 0) return; e.preventDefault(); resizePointer={id:e.pointerId,x:e.screenX,y:e.screenY,size:petSize}; resizeCorner.setPointerCapture(e.pointerId); });",
  "  resizeCorner.addEventListener('pointermove', function(e){ if(!resizePointer || resizePointer.id !== e.pointerId) return; var delta=((e.screenX-resizePointer.x)+(e.screenY-resizePointer.y))/2; act({type:'resize',size:Math.max(72,Math.min(160,Math.round(resizePointer.size+delta)))}); });",
  "  ['pointerup','pointercancel','lostpointercapture'].forEach(function(type){resizeCorner.addEventListener(type,function(){resizePointer=null;});});",
  "  resizeCorner.addEventListener('keydown',function(e){if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].indexOf(e.key)<0)return;e.preventDefault();act({type:'resize',size:petSize+(['ArrowUp','ArrowRight'].indexOf(e.key)>=0?8:-8)});});",
  "}",
  "var toggleButton = document.getElementById('toggle');",
  "var petPointer = null, suppressPetClick = false;",
  "if (toggleButton) toggleButton.addEventListener('pointerdown', function(event){",
  "  if (expanded || event.button !== 0 || SURFACE !== 'teacher-rail') return;",
  "  petPointer = { id: event.pointerId, x: event.screenX, y: event.screenY, moved: false }; suppressPetClick = false;",
  "  toggleButton.setPointerCapture(event.pointerId); toggleButton.dataset.pressed = 'true';",
  "  act({ type: 'drag-start', x: event.screenX, y: event.screenY });",
  "});",
  "if (toggleButton) toggleButton.addEventListener('pointermove', function(event){",
  "  if (!petPointer || petPointer.id !== event.pointerId) return;",
  "  if (Math.hypot(event.screenX-petPointer.x,event.screenY-petPointer.y) >= 5) petPointer.moved = true;",
  "  if (petPointer.moved) { toggleButton.dataset.pressed = 'false'; act({ type: 'drag-move', x: event.screenX, y: event.screenY }); }",
  "});",
  "function endPetDrag(event){ if (!petPointer || petPointer.id !== event.pointerId) return; suppressPetClick = petPointer.moved || event.type !== 'pointerup'; petPointer = null; toggleButton.dataset.pressed = 'false'; act({ type: 'drag-end' }); }",
  "if (toggleButton) ['pointerup','pointercancel','lostpointercapture'].forEach(function(type){ toggleButton.addEventListener(type,endPetDrag); });",
  "window.addEventListener('blur', function(){ if (petPointer) endPetDrag({ pointerId: petPointer.id, type: 'blur' }); });",
  "if (toggleButton) toggleButton.addEventListener('click', function(event){ if (suppressPetClick) { suppressPetClick = false; return; } setExpanded(!expanded, true); });",
  "if (toggleButton) toggleButton.addEventListener('keydown', function(event){ if (event.key === 'Enter' || event.key === ' ') suppressPetClick = false; });",
  "document.addEventListener('keydown', function(event){ if (event.key === 'Escape' && expanded && SURFACE === 'teacher-rail') { setExpanded(false, true); toggleButton.focus({ preventScroll: true }); } });",
  "document.getElementById('hide').addEventListener('click', function(){ act({ type: 'hide' }); });",
  "document.getElementById('open').addEventListener('click', function(){ act({ type: 'open' }); });",
  "if (bridge && bridge.onSnapshot) bridge.onSnapshot(applyMainState);",
  "if (bridge && bridge.onHealth) bridge.onHealth(setSyncHealth);",
  "if (toggleButton) setExpanded(expanded, false);",
  "setSyncHealth({ status: 'waiting' });",
  "act({ type: 'sync' });",
].join("\n");

const POPUP_SCRIPT = [
  PAGE_HELPERS,
  BLOUB_MOTION_SOURCE,
  "var popupMotion=MochiMotion.mountMotion(document.querySelector('.popup-pet .pet__orb'),{state:'alert'});",
  "window.addEventListener('pagehide',function(){popupMotion.dispose();pauseHide();clearTimeout(leaveTimer);},{once:true});",
  "var current = null;",
  "var receiptPending = false;",
  "var hideTimer = null, leaveTimer = null, remaining = 30000, startedAt = 0;",
  "function pauseHide(){if(hideTimer !== null){clearTimeout(hideTimer);hideTimer=null;remaining=Math.max(0,remaining-(Date.now()-startedAt));}}",
  "function dismissAnimated(){if(!current || receiptPending || leaveTimer !== null)return;pauseHide();var id=current.id;document.body.dataset.leaving='true';leaveTimer=setTimeout(function(){leaveTimer=null;if(current && current.id===id)act({type:'dismiss',id:id});},matchMedia('(prefers-reduced-motion: reduce)').matches?0:220);}",
  "function resumeHide(){if(!current || receiptPending || hideTimer !== null || leaveTimer !== null || document.body.matches(':hover') || document.querySelector('.pop').contains(document.activeElement))return;startedAt=Date.now();hideTimer=setTimeout(dismissAnimated,remaining);}",
  "document.body.addEventListener('mouseenter',pauseHide);document.body.addEventListener('mouseleave',resumeHide);",
  "document.addEventListener('focusin',pauseHide);document.addEventListener('focusout',function(){setTimeout(resumeHide,0);});",
  "document.getElementById('p-close').addEventListener('click',dismissAnimated);",
  "function receiptFits(){",
  "  var body = document.querySelector('.pop__body');",
  "  var bar = document.querySelector('.pop__bar').getBoundingClientRect();",
  "  var actions = document.querySelector('.pop__actions').getBoundingClientRect();",
  "  var area = body.getBoundingClientRect();",
  "  if (body.scrollHeight > body.clientHeight + 1 || area.bottom > actions.top - 3) return false;",
  "  return ['p-title','p-subject','p-detail'].every(function(id){ var rect = document.getElementById(id).getBoundingClientRect(); return rect.top >= Math.max(area.top, bar.bottom) - 1 && rect.bottom <= area.bottom + 1; });",
  "}",
  "function render(payload){",
  "  pauseHide();clearTimeout(leaveTimer);leaveTimer=null;remaining=30000;delete document.body.dataset.leaving;",
  "  current = payload;",
  "  receiptPending = false;",
  "  document.getElementById('p-title').textContent = payload.title || '叮咚，Mochi 来送信啦～';",
  "  document.getElementById('p-subject').textContent = payload.subject || '';",
  "  document.getElementById('p-detail').textContent = payload.detail || '';",
  "  document.getElementById('p-stamp').textContent = payload.at ? stamp(payload.at) : '';",
  "  document.getElementById('p-feedback').textContent = '';",
  "  document.querySelector('.pop__body').scrollTop = 0;",
  "  var button = document.getElementById('p-ack'); button.disabled = false; button.textContent = payload.receiptMessageId && receiptFits() ? '我已看到' : '关闭提醒';",
  "  resumeHide();",
  "}",
  "document.getElementById('p-ack').addEventListener('click', function(){",
  "  if (!current || receiptPending) return;",
  "  if (!current.receiptMessageId || this.textContent === '关闭提醒') { dismissAnimated(); return; }",
  "  if (!receiptFits()) { if (this.textContent !== '关闭提醒') { this.textContent = '关闭提醒'; document.getElementById('p-feedback').textContent = '内容未完整显示，请打开 Mochi 查看。'; return; } act({ type: 'dismiss', id: current.id }); return; }",
  "  pauseHide(); receiptPending = true; this.disabled = true; this.textContent = '确认中…';",
  "  document.getElementById('p-feedback').textContent = '';",
  "  act({ type: 'acknowledge', id: current.id });",
  "});",
  "document.getElementById('p-open').addEventListener('click', function(){",
  "  act({ type: 'open', id: current ? current.id : '' });",
  "});",
  "document.addEventListener('keydown', function(event){",
  "  if (event.key !== 'Escape' || !current) return;",
  "  dismissAnimated();",
  "});",
  "if (bridge && bridge.onReceiptFeedback) bridge.onReceiptFeedback(function(result){",
  "  if (!current || !result || result.id !== current.id) return;",
  "  if (result.ok) return;",
  "  receiptPending = false; var button = document.getElementById('p-ack'); button.disabled = false; button.textContent = '重试确认';",
  "  document.getElementById('p-feedback').textContent = result.message || '确认失败，请重试。';",
  "});",
  "if (bridge && bridge.onPopup) bridge.onPopup(render);",
  "act({ type: 'sync' });",
].join("\n");

function document_(title: string, surface: RailSurface | "popup", extraCss: string, body: string, script: string, expanded?: boolean): string {
  return [
    "<!doctype html>",
    "<html lang='zh-CN'><head><meta charset='utf-8'>",
    "<meta http-equiv='Content-Security-Policy' content=\"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'\">",
    "<title>", title, "</title>",
    "<style>:root{", PALETTE, "}", BASE_CSS, "\n", extraCss, MOCHI_CONTROLS_CSS, MOCHI_PET_CSS, "</style>",
    "</head>",
    "<body data-mochi-native data-surface='", surface, "'", expanded === undefined ? "" : ` data-expanded='${expanded}'`, " data-sync='waiting'>",
    body,
    "<script>", script, "</script>",
    "</body></html>",
  ].join("");
}

const RAIL_BODY = [
  "<div class='shell shell--teacher' id='shell'>",
  "<button id='pet-resize' type='button' aria-label='调整 Mochi 大小'></button>",
  "<header class='drag'>",
  "<button class='icon nodrag' id='toggle' type='button' aria-controls='list' aria-expanded='false' aria-label='展开 Mochi 待办'>",
  "<span class='pet' aria-hidden='true'><svg class='pet__orb' viewBox='0 0 100 100' focusable='false'>",
  "<ellipse class='pet__shadow' cx='50' cy='93.5' rx='25' ry='4.2'/>",
  "<path class='pet__body' d='M 93.50 50.00 C 93.64 58.25, 89.57 68.46, 84.46 75.04 C 79.35 81.62, 70.70 87.08, 62.83 89.47 C 54.95 91.87, 44.90 91.95, 37.19 89.41 C 29.49 86.88, 21.51 80.84, 16.59 74.27 C 11.67 67.70, 8.01 58.32, 7.69 50.00 C 7.38 41.68, 9.82 31.02, 14.70 24.35 C 19.59 17.69, 29.06 12.07, 37.00 10.00 C 44.95 7.92, 54.61 9.30, 62.38 11.90 C 70.15 14.49, 78.46 19.20, 83.65 25.55 C 88.84 31.90, 93.37 41.75, 93.50 50.00 Z'/>",
  "<g transform='translate(50 52)'><g class='pet__gaze'><g class='pet__eyes'><ellipse cx='-11' cy='0' rx='5.6' ry='7.2'/><ellipse cx='11' cy='0' rx='5.6' ry='7.2'/></g></g></g></svg>",
  "<svg class='pet__laptop' viewBox='24 10 72 54' focusable='false'><ellipse cx='60' cy='58' fill='rgba(46,26,10,.15)' rx='36' ry='3.6'/><g>",
  "<rect fill='#4A3826' height='37' rx='5' width='54' x='33' y='11'/><rect fill='#2E2318' height='30' rx='3' width='48' x='36' y='14.5'/><g fill='#FFE7C2'>",
  "<rect class='pet__glyph' height='2.8' rx='1.4' width='11' x='40' y='20'/><rect class='pet__glyph' height='2.8' rx='1.4' width='16' x='40' y='26.5'/><rect class='pet__glyph' height='2.8' rx='1.4' width='7' x='40' y='33'/><rect class='pet__glyph' height='2.8' rx='1.4' width='12' x='60' y='26.5'/><rect class='pet__glyph' height='2.8' rx='1.4' width='8' x='60' y='33'/></g>",
  "<path d='M26 52.5 L94 52.5 L87 49.5 L33 49.5 Z' fill='#6B4E33'/><rect fill='#7A5C3E' height='3.6' rx='1.8' width='70' x='25' y='51.1'/></g></svg>",
  "<span class='pet__thought' aria-hidden='true'><i></i><i></i><i></i></span><svg id='pet-count-group' viewBox='0 0 20 20' aria-hidden='true'><circle cx='10' cy='10' r='9' fill='#cfaf80' stroke='var(--mochi-canvas)' stroke-width='1.5'/><text id='pet-count' x='10' y='13.2' text-anchor='middle' fill='#1d2a23' font-size='10' font-weight='700'>0</text></svg></span><svg class='toggle-mark' aria-hidden='true' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round'><path d='M6 12h12'/></svg></button>",
  "<h1 id='heading'>待办</h1>",
  "<span class='count' id='count' hidden>0</span>",
  "<button class='icon nodrag' id='hide' type='button' title='隐藏' aria-label='隐藏常驻条'><svg aria-hidden='true' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round'><path d='m7 7 10 10M17 7 7 17'/></svg></button>",
  "</header>",
  "<div class='list' id='list' role='region' aria-live='polite' aria-label='待办列表'></div>",
  "<div class='departures' id='departures' aria-hidden='true'></div>",
  "<footer class='drag'><span id='detail'></span><span class='grow'></span><span id='updated'></span>",
  "<button class='nodrag' id='open' type='button'>打开 Mochi</button></footer>",
  "</div>",
  "<div class='sr-only' id='sync-announcement' role='status' aria-live='polite'></div>",
].join("");

const POPUP_AVATAR = RAIL_BODY.match(/<svg class='pet__orb'[\s\S]*?<\/svg>/u)?.[0] ?? "";
const POPUP_BODY = [
  "<div class='popup-pet' aria-hidden='true'>", POPUP_AVATAR, "</div>",
  "<div class='pop drag'>",
  "<div class='pop__bar'>Mochi · 小纸条<span class='grow'></span><span id='p-stamp'></span><button class='pop__close nodrag' id='p-close' type='button' aria-label='收起提醒'>×</button></div>",
  "<div class='pop__body'>",
  "<h1 class='pop__title' id='p-title'>叮咚，Mochi 来送信啦～</h1>",
  "<div class='pop__subject' id='p-subject'></div>",
  "<div class='pop__detail' id='p-detail'></div>",
  "</div>",
  "<div class='pop__feedback' id='p-feedback' role='status' aria-live='polite'></div>",
  "<div class='pop__actions'>",
  "<button class='primary nodrag' id='p-ack' type='button'>我知道了</button>",
  "<button class='nodrag' id='p-open' type='button'>打开 Mochi</button>",
  "</div>",
  "</div>",
].join("");

/** 教师端小横条 / 教室端常驻屏共用同一份标记，差异由 surface 决定。 */
export function railPageHtml(surface: RailSurface): string {
  const title = surface === "classroom-board" ? "Mochi 课堂名单" : "Mochi 待办";
  const body = surface === "classroom-board"
    ? RAIL_BODY.replace(" class='shell shell--teacher'", " class='shell'").replace(/<button\b[^>]*id='toggle'[\s\S]*?<\/button>/u, "")
    : RAIL_BODY;
  return document_(title, surface, surface === "classroom-board" ? BOARD_CSS : "", body, RAIL_SCRIPT, surface === "classroom-board");
}

/** 喊人弹窗。桌宠气泡：30秒后收起，悬停/键盘操作暂停；收起不代表已读。 */
export function popupPageHtml(): string {
  return document_("Mochi 小纸条", "popup", POPUP_CSS, POPUP_BODY, POPUP_SCRIPT);
}
